# Generated by Django 5.2.17 on 2026-09-25 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('algorithm', models.CharField(default='DecisionTreeClassifier', max_length=80)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('class_metrics', models.JSONField(default=dict)),
                ('feature_names', models.JSONField(default=list)),
                ('training_rows', models.PositiveIntegerField()),
                ('test_rows', models.PositiveIntegerField()),
                ('artifact_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_sample', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.CharField(db_index=True, max_length=2)),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low risk'), ('medium', 'Medium risk'), ('high', 'High risk')], db_index=True, max_length=20)),
                ('feature_snapshot', models.JSONField(default=dict)),
                ('data_status', models.CharField(default='complete', max_length=20)),
                ('is_sample', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='academics.course')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='analytics.modelversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_requested', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'risk_level'], name='analytics_p_student_a69f3d_idx')],
            },
        ),
    ]
